version: '3.7'
services:
  node-explorer:
    image: r3dockerhub/node-explorer:v0.1.2
    ports:
      - "30361:80" #TODO:set before image creation
    restart: always
    depends_on:
      - node-server

  node-server:
    image: r3dockerhub/node-server:v0.1.2
    ports:
      - "30463:8580" #TODO:set before image creation
    restart: always
    volumes:
      - ${CORDAPPS_PATH}:/cordapps
    network_mode: "host"
